import { Agent, Listing, Testimonial, SiteConfig } from './types'

// Demo data for template preview - this will be replaced by REL8TION API data
export const demoAgent: Agent = {
  id: 'demo-agent-001',
  name: 'Sarah Mitchell',
  title: 'Luxury Real Estate Specialist',
  email: 'sarah@mitchellrealty.com',
  phone: '(555) 123-4567',
  photo: '/images/agent-placeholder.png',
  bio: `With over 15 years of experience in luxury real estate, I specialize in helping clients find their dream homes in the most prestigious neighborhoods. My commitment to exceptional service and deep market knowledge has made me one of the top-producing agents in the region.

I believe that buying or selling a home should be an exciting journey, not a stressful ordeal. That's why I provide personalized attention to every client, ensuring their unique needs are met at every step of the process.

Whether you're a first-time buyer or looking to invest in luxury properties, I'm here to guide you through every aspect of the transaction with expertise and integrity.`,
  specializations: ['Luxury Homes', 'Waterfront Properties', 'Investment Properties', 'First-Time Buyers'],
  yearsExperience: 15,
  licenseNumber: 'RE-12345678',
  brokerage: 'Mitchell & Associates Realty',
  socialLinks: {
    instagram: 'https://instagram.com/sarahmitchellrealty',
    facebook: 'https://facebook.com/sarahmitchellrealty',
    linkedin: 'https://linkedin.com/in/sarahmitchell',
    youtube: 'https://youtube.com/@sarahmitchellrealty',
  },
  testimonials: [],
  stats: {
    totalSales: 85000000,
    propertiesSold: 127,
    avgDaysOnMarket: 21,
    clientSatisfaction: 98,
  },
}

export const demoTestimonials: Testimonial[] = [
  {
    id: 't1',
    clientName: 'Michael & Jennifer Thompson',
    text: 'Sarah made our dream of owning a waterfront property a reality. Her knowledge of the market and negotiation skills saved us thousands. We couldn\'t have asked for a better agent!',
    rating: 5,
    date: '2024-03-15',
    propertyType: 'Waterfront Home',
  },
  {
    id: 't2',
    clientName: 'David Chen',
    text: 'As a first-time investor, I was nervous about the process. Sarah\'s patience and expertise guided me through every step. I\'ve since purchased two more properties with her help.',
    rating: 5,
    date: '2024-02-28',
    propertyType: 'Investment Property',
  },
  {
    id: 't3',
    clientName: 'The Rodriguez Family',
    text: 'We relocated from out of state and Sarah went above and beyond to help us find the perfect family home. Her virtual tours and detailed neighborhood guides made the process seamless.',
    rating: 5,
    date: '2024-01-10',
    propertyType: 'Single Family Home',
  },
]

export const demoListings: Listing[] = [
  {
    id: 'l1',
    title: 'Stunning Waterfront Estate',
    address: '1234 Oceanview Drive',
    city: 'Malibu',
    state: 'CA',
    zipCode: '90265',
    price: 4500000,
    bedrooms: 5,
    bathrooms: 6,
    squareFeet: 6200,
    lotSize: 0.75,
    yearBuilt: 2019,
    propertyType: 'house',
    status: 'active',
    description: 'Breathtaking oceanfront estate with panoramic views, private beach access, and resort-style amenities.',
    features: ['Ocean Views', 'Private Beach', 'Infinity Pool', 'Smart Home', 'Wine Cellar', 'Home Theater'],
    images: ['/images/listing-1.png'],
    listedDate: '2024-03-01',
  },
  {
    id: 'l2',
    title: 'Modern Downtown Penthouse',
    address: '500 Skyline Tower, PH1',
    city: 'Los Angeles',
    state: 'CA',
    zipCode: '90012',
    price: 2850000,
    bedrooms: 3,
    bathrooms: 3.5,
    squareFeet: 3800,
    yearBuilt: 2022,
    propertyType: 'condo',
    status: 'active',
    description: 'Ultra-modern penthouse with floor-to-ceiling windows offering stunning city skyline views.',
    features: ['City Views', 'Private Terrace', 'Concierge', 'Gym Access', 'Rooftop Pool', 'Valet Parking'],
    images: ['/images/listing-2.png'],
    listedDate: '2024-02-15',
  },
  {
    id: 'l3',
    title: 'Spanish Colonial Revival',
    address: '789 Heritage Lane',
    city: 'Santa Barbara',
    state: 'CA',
    zipCode: '93101',
    price: 3200000,
    bedrooms: 4,
    bathrooms: 4,
    squareFeet: 4500,
    lotSize: 0.5,
    yearBuilt: 1928,
    propertyType: 'house',
    status: 'pending',
    description: 'Meticulously restored Spanish Colonial masterpiece with original details and modern updates.',
    features: ['Historic Character', 'Courtyard', 'Guest House', 'Gardens', 'Mountain Views', 'Updated Kitchen'],
    images: ['/images/listing-3.png'],
    listedDate: '2024-01-20',
  },
  {
    id: 'l4',
    title: 'Luxury Beachfront Condo',
    address: '2100 Pacific Coast Highway #401',
    city: 'Laguna Beach',
    state: 'CA',
    zipCode: '92651',
    price: 1950000,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1800,
    yearBuilt: 2020,
    propertyType: 'condo',
    status: 'active',
    description: 'Turn-key beachfront living with designer finishes and unobstructed ocean views.',
    features: ['Beachfront', 'Designer Finishes', 'Balcony', 'Secured Building', 'Beach Access', 'Parking'],
    images: ['/images/listing-4.png'],
    listedDate: '2024-03-10',
  },
  {
    id: 'l5',
    title: 'Contemporary Hillside Villa',
    address: '456 Summit Ridge Road',
    city: 'Beverly Hills',
    state: 'CA',
    zipCode: '90210',
    price: 7800000,
    bedrooms: 6,
    bathrooms: 8,
    squareFeet: 9500,
    lotSize: 1.2,
    yearBuilt: 2021,
    propertyType: 'house',
    status: 'active',
    description: 'Architectural masterpiece with sweeping canyon views, designed by a renowned architect.',
    features: ['Canyon Views', 'Infinity Edge Pool', 'Home Gym', 'Theater Room', 'Wine Room', 'Smart Home'],
    images: ['/images/listing-5.png'],
    listedDate: '2024-02-01',
  },
  {
    id: 'l6',
    title: 'Charming Craftsman Bungalow',
    address: '321 Oak Street',
    city: 'Pasadena',
    state: 'CA',
    zipCode: '91101',
    price: 1450000,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 2200,
    lotSize: 0.25,
    yearBuilt: 1925,
    propertyType: 'house',
    status: 'sold',
    description: 'Beautifully preserved Craftsman with original woodwork, updated for modern living.',
    features: ['Original Details', 'Built-ins', 'Hardwood Floors', 'Front Porch', 'Garden', 'Detached Garage'],
    images: ['/images/listing-6.png'],
    listedDate: '2023-12-01',
    soldDate: '2024-02-15',
    soldPrice: 1475000,
  },
]

// Demo site configuration
export const demoSiteConfig: SiteConfig = {
  agentId: 'demo-agent-001',
  slug: 'sarah-mitchell',
  customDomain: null,
  colorScheme: {
    id: 'warm-earth',
    name: 'Warm Earth',
    primary: '#8B7355',
    secondary: '#f5f5f0',
    accent: '#6B8E6B',
    text: '#1a1a1a',
    background: '#ffffff',
    muted: '#6b7280',
  },
  fontPairing: 'classic-elegant',
  isPublished: true,
  createdAt: '2024-01-01',
  updatedAt: '2024-03-15',
}
