create table if not exists public.property_keepsakes (
  id uuid primary key default gen_random_uuid(),
  public_code text not null unique,
  attribution_key text not null unique,
  open_house_id text not null,
  open_house_event_id uuid references public.open_house_events(id) on delete set null,
  field_demo_visit_id uuid references public.field_demo_visits(id) on delete set null,
  listing_agent_id uuid references public.listing_agents(id) on delete set null,
  loan_officer_uid uuid references public.verified_profiles(uid) on delete set null,
  status text not null default 'active' check (status in ('active', 'retired')),
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists property_keepsakes_open_house_idx
  on public.property_keepsakes (open_house_id, created_at desc);

create index if not exists property_keepsakes_visit_idx
  on public.property_keepsakes (field_demo_visit_id)
  where field_demo_visit_id is not null;

create index if not exists property_keepsakes_event_idx
  on public.property_keepsakes (open_house_event_id)
  where open_house_event_id is not null;

create index if not exists property_keepsakes_listing_agent_idx
  on public.property_keepsakes (listing_agent_id)
  where listing_agent_id is not null;

create index if not exists property_keepsakes_loan_officer_idx
  on public.property_keepsakes (loan_officer_uid)
  where loan_officer_uid is not null;

alter table public.property_keepsakes enable row level security;
revoke all on table public.property_keepsakes from anon, authenticated;
revoke all on table public.property_keepsakes from service_role;
grant select, insert, update on table public.property_keepsakes to service_role;

comment on table public.property_keepsakes is
  'Durable HomeKey public codes and relationship attribution. Property facts remain in the existing open-house/property profile pipeline.';

create table if not exists public.property_keepsake_events (
  id bigint generated by default as identity primary key,
  property_keepsake_id uuid not null references public.property_keepsakes(id) on delete cascade,
  event_type text not null check (event_type in (
    'homekey_viewed',
    'home_saved',
    'agent_relationship_requested',
    'agent_contact_clicked',
    'loan_officer_contact_clicked',
    'similar_homes_requested',
    'off_market_requested',
    'price_alert_requested',
    'different_area_requested',
    'financing_requested'
  )),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists property_keepsake_events_key_time_idx
  on public.property_keepsake_events (property_keepsake_id, created_at desc);

create index if not exists property_keepsake_events_type_time_idx
  on public.property_keepsake_events (event_type, created_at desc);

alter table public.property_keepsake_events enable row level security;
revoke all on table public.property_keepsake_events from anon, authenticated;
revoke all on sequence public.property_keepsake_events_id_seq from anon, authenticated;
revoke all on table public.property_keepsake_events from service_role;
revoke all on sequence public.property_keepsake_events_id_seq from service_role;
grant select, insert on table public.property_keepsake_events to service_role;
grant usage, select on sequence public.property_keepsake_events_id_seq to service_role;

comment on table public.property_keepsake_events is
  'Minimal server-written HomeKey interaction events without raw visitor identity or activation data.';

alter table public.leads
  add column if not exists source text,
  add column if not exists source_key text,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists leads_source_key_unique_idx
  on public.leads (source_key);

create index if not exists leads_source_created_idx
  on public.leads (source, created_at desc);

comment on column public.leads.source is
  'Stable product surface that created or most recently updated this lead.';

comment on column public.leads.source_key is
  'Server-generated idempotency key for source-specific lead upserts.';

comment on column public.leads.metadata is
  'Server-managed structured source context, preferences, and consent evidence.';
